/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - ssotme odxml42/odxml-to-csharp-pocos
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace crossmegame.Lib.DataClasses
{                   
    
    public partial class LevelCell 
    {
        public LevelCell()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("LevelCell: {0}", this.Name);
        }
                            
    }
}